### ISSUE TITLE
/bin/bash: not found

### ISSUE THREAD

**Issue by bencehezso** [microsoft/ga4gh-tes#231]
**Describe the bug**
My client utilizes CromwellOnAzure to orchestrate the computing tasks needed for genomics analysis. The client uses custom scientific workflows that were executed successfully multiple times on CoA 3.2.. however, there is a failure when attempting to run them on CoA 4.3. (We initiated preparations for upgrading to version 3.4 last year, but considering that version 4 was released earlier this year, we have decided to proceed with the upgrade to the latest version available.)

The error message below can be found in the stderr.txt file within the cromwell-executions directory:
`/usr/local/bin/docker-entrypoint.sh: exec: line 61: /bin/bash: not found`

Cromwell pod logs:
```
2023-05-23 17:46:36 cromwell-system-akka.dispatchers.backend-dispatcher-201049 INFO  - TesAsyncBackendJobExecutionActor [UUID(a2277c08)xyz_cloud_validation.run_nested_cromwell:NA:2]: TES reported a failure for Job a2277c08_db8461eba59248fba1a63a13dbc767a5: 'EXECUTOR_ERROR'
2023-05-23 17:46:36 cromwell-system-akka.dispatchers.backend-dispatcher-201053 INFO  - TesAsyncBackendJobExecutionActor [UUID(a2277c08)xyz_cloud_validation.run_nested_cromwell:NA:2]: Status change from Running to EXECUTOR_ERROR
2023-05-23 17:46:37 cromwell-system-akka.dispatchers.engine-dispatcher-10 INFO  - WorkflowManagerActor: Workflow a2277c08-55ef-463c-b675-1c89c742f8a6 failed (during ExecutingWorkflowState): common.exception.AggregatedMessageException: Task xyz_cloud_validation.run_nested_cromwell:NA:2 failed for unknown reason: EXECUTOR_ERROR:
FailureExitCode
Batch task ExitCode: 127, Failure message: The task exited with an exit code representing a failure
Message: The task process exited with an unexpected exit code
AdditionalErrorCode: FailureExitCode
	at cromwell.backend.impl.tes.TesAsyncBackendJobExecutionActor.handleExecutionError(TesAsyncBackendJobExecutionActor.scala:281)
	at cromwell.backend.impl.tes.TesAsyncBackendJobExecutionActor.handleExecutionFailure(TesAsyncBackendJobExecutionActor.scala:288)
	at cromwell.backend.impl.tes.TesAsyncBackendJobExecutionActor.handleExecutionFailure(TesAsyncBackendJobExecutionActor.scala:63)
	at cromwell.backend.standard.StandardAsyncExecutionActor$$anonfun$handleExecutionResult$11.applyOrElse(StandardAsyncExecutionActor.scala:1346)
	at cromwell.backend.standard.StandardAsyncExecutionActor$$anonfun$handleExecutionResult$11.applyOrElse(StandardAsyncExecutionActor.scala:1342)
	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:490)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:41)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:49)
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

2023-05-23 17:46:42 cromwell-system-akka.dispatchers.engine-dispatcher-29 INFO  - WorkflowManagerActor: Workflow actor for a2277c08-55ef-463c-b675-1c89c742f8a6 completed with status 'Failed'. The workflow will be removed from the workflow store.
```
Based on the error message, my first idea was that the error may be in the [BatchScheduler](https://github.com/microsoft/ga4gh-tes/blob/e25c541f1ff8343df9548c7e0e6ec6166031ddca/src/TesApi.Web/BatchScheduler.cs#L1120), because the __batch directory contains the download and upload scripts, while the metrics.txt file is not present.

FYI
- The custom scientific workflow is based on ubuntu:22.04.
- The test wdl was executed and passed.

**Steps to Reproduce**
I can't share the custom workflow.

**Expected behavior**
The bash executable is available on both the Batch managed virtual machines (nodes) and the containers, so I really don't understand the error message.

**Deployment details:**
The company manages the infrastructure components (Azure resources) using Terraform. 
(The setup is based on the CoA deployment approach..)

The test wdl was executed and passed, so I don't think that the issue is related to the infrastructure.

**Screenshots**
No.

**Additional context**
No.

**Comment by bencehezso** [comment]
@giventocode @MattMcL4475 
I know you're quite busy with the other bugs and features, but do you have any tips or ideas on how can I move this forward?

**Comment by bencehezso** [comment]
@BMurri 
Thanks for getting back to me!

1) 
The User-assigned Managed identity has a Contributor role assignment for the Azure Container Registry. (No anonymous access is allowed and the Batch managed virtual machine was able to pull the image..)
2) 
The stderr.txt only contains the following error message: 
`/usr/local/bin/docker-entrypoint.sh: exec: line 61: /bin/bash: not found`
The stdout.txt is empty.

**Comment by BMurri** [comment]
You will need to either:
 * make sure all steps from this [link](https://github.com/microsoft/CromwellOnAzure/wiki/Customizing-Your-Instance#2-setting-up-authentication-to-your-acr-using-the-coa-managed-identity) have been completed (use the same deployer with which you most recently applied to your deployment), or
 * turn on anonymous access and revoke authenticated access from the managed identity.

**Comment by bencehezso** [comment]
@BMurri 
Sorry for not getting back to you sooner.

It was my fault, apologies for the false alarm.
CoA's default docker image was missing from the private ACR, which was reason for the error message.
