### ISSUE TITLE
Solution no longer builds from Visual Studio on Windows without first building from the command line ("The "GenerateMD5" task failed unexpectedly")

### ISSUE THREAD

**Issue by MattMcL4475** [microsoft/ga4gh-tes#265]
**Describe the bug**
`main` no longer builds from Visual Studio on Windows until you first run "dotnet build" from the command line in the root of the repo.  The error is `The "GenerateMD5" task failed unexpectedly`

**Workaround**
Run `dotnet build` from the command line in the solution folder

**Steps to Reproduce**
Clone main, open solution, build

**Expected behavior**
The solution builds

Severity    Code    Description    Project    File    Line    Suppression State
Error    MSB4018    The "GenerateMD5" task failed unexpectedly.
System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\m\Source\Repos\microsoft\ga4gh-tes\src\TesApi.Web\bin\Debug\net7.0\scripts\tRunner'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.File.InternalReadAllBytes(String path, Boolean checkHost)
   at InlineCode.GenerateMD5.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()    TesApi.Web    C:\Users\m\Source\Repos\microsoft\ga4gh-tes\src\TesApi.Web\TesApi.Web.csproj    127

**Comment by BMurri** [comment]
Three part fix:
* Add build code to publish/create/co-locate `tRunner` and `TRunnerMD5Hash.txt` into the correct location in the `TesApi.Web` published artifacts.
* Add build step to official build to call this new code. Make it conditional to prevent build breaks in PRs that don't (yet) contain the new code from the previous step.
* Remove current build code in TesApi.Web.csproj to publish/create/co-locate `tRunner` and `TRunnerMD5Hash.txt`.

Note that steps 1 & 3 involve PRs. Step 2 will be invisible from the POV of this repository.
