### ISSUE TITLE
Workflow fails when PricingApi look up fails. 

### ISSUE THREAD

**Issue by jsaun** [microsoft/ga4gh-tes#473]
**Describe the bug**
Tes is throwing and reporting an error back to cromwell when fetching the current prices fails. 

**Expected behavior**
Fall back to cached prices, or the initial static prices file. 

Stack trace:
2023-10-19 22:51:38 cromwell-system-akka.dispatchers.engine-dispatcher-56 INFO  - WorkflowManagerActor: Workflow 64fd9b53-caa1-4784-9950-a169c589614c failed (during ExecutingWorkflowState): common.exception.AggregatedMessageException: Task large_deletion_workflow.vardict:0:2 failed for unknown reason: SYSTEM_ERROR:UnknownError
System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(QueueItem queueItem)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.HttpConnectionWaiter`1.WaitForConnectionAsync(Boolean async, CancellationToken requestCancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at TesApi.Web.Management.Clients.HttpApiClient.ExecuteRequestAndReadResponseBodyAsync(HttpRequestMessage request) in D:\a\1\s\src\ga4gh-tes\src\TesApi.Web\Management\Clients\HttpApiClient.cs:line 227
   at TesApi.Web.Management.Clients.HttpApiClient.<>c__DisplayClass17_0.<<HttpGetRequestWithRetryPolicyAsync>b__0>d.MoveNext() in D:\a\1\s\src\ga4gh-tes\src\TesApi.Web\Management\Clients\HttpApiClient.cs:line 16440--- End of stack trace from previous location ---
   at Polly.Retry.AsyncRetryEngine.ImplementationAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, ExceptionPredicates shouldRetryExceptionPredicates, ResultPredicates`1 shouldRetryResultPredicates, Func`5 onRetryAsync, Int32 permittedRetryCount, IEnumerable`1 sleepDurationsEnumerable, Func`4 sleepDurationProvider, Boolean continueOnCapturedContext)
   at Polly.AsyncPolicy.ExecuteAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, Boolean continueOnCapturedContext)
   at TesApi.Web.Management.Clients.HttpApiClient.HttpGetRequestWithRetryPolicyAsync(Uri requestUrl, Boolean setAuthorizationHeader) in D:\a\1\s\src\ga4gh-tes\src\TesApi.Web\Management\Clients\HttpApiClient.cs:line 159
   at TesApi.Web.Management.Clients.HttpApiClient.HttpGetRequestAsync(Uri requestUrl, Boolean setAuthorizationHeader, Boolean cacheResults) in D:\a\1\s\src\ga4gh-tes\src\TesApi.Web\Management\Clients\HttpApiClient.cs:line 112
   at TesApi.Web.Management.Clients.HttpApiClient.HttpGetRequestAsync[TResponse](Uri requestUrl, Boolean setAuthorizationHeader, Boolean cacheResults) in D:\a\1\s\src\ga4gh-tes\src\TesApi.Web\Management\Clients\HttpApiClient.cs:line 126
   at TesApi.Web.Management.Clients.PriceApiClient.GetPricingInformationPageAsync(Int32 skip, String region, Boolean cacheResults) in D:\a\1\s\src\ga4gh-tes\src\TesApi.Web\Management\Clients\PriceApiClient.cs:line 79
   at TesApi.Web.Management.Clients.PriceApiClient.GetAllPricingInformationAsync(String region, Boolean cacheResults)+MoveNext() in D:\a\1\s\src\ga4gh-tes\src\TesApi.Web\Management\Clients\PriceApiClient.cs:line 41
   at TesApi.Web.Management.Clients.PriceApiClient.GetAllPricingInformationAsync(String region, Boolean cacheResults)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
   at System.Linq.AsyncEnumerable.WhereEnumerableAsyncIteratorWithTask`1.MoveNextCore() in /_/Ix.NET/Source/System.Linq.Async/System/Linq/Operators/Where.cs:line 294
   at System.Linq.AsyncIteratorBase`1.MoveNextAsync() in /_/Ix.NET/Source/System.Linq.Async/System/Linq/AsyncIterator.cs:line 70
   at System.Linq.AsyncIteratorBase`1.MoveNextAsync() in /_/Ix.NET/Source/System.Linq.Async/System/Linq/AsyncIterator.cs:line 75
   at System.Linq.AsyncEnumerable.<ToListAsync>g__Core|424_0[TSource](IAsyncEnumerable`1 source, CancellationToken cancellationToken) in /_/Ix.NET/Source/System.Linq.Async/System/Linq/Operators/ToList.cs:line 36
   at System.Linq.AsyncEnumerable.<ToListAsync>g__Core|424_0[TSource](IAsyncEnumerable`1 source, CancellationToken cancellationToken) in /_/Ix.NET/Source/System.Linq.Async/System/Linq/Operators/ToList.cs:line 36
   at TesApi.Web.Management.PriceApiBatchSkuInformationProvider.GetVmSizesAndPricesAsyncImpl(String region) in D:\a\1\s\src\ga4gh-tes\src\TesApi.Web\Management\PriceApiBatchSkuInformationProvider.cs:line 72
   at TesApi.Web.Management.PriceApiBatchSkuInformationProvider.<>c__DisplayClass5_0.<<GetVmSizesAndPricesAsync>b__0>d.MoveNext() in D:\a\1\s\src\ga4gh-tes\src\TesApi.Web\Management\PriceApiBatchSkuInformationProvider.cs:line 6424--- End of stack trace from previous location ---
   at LazyCache.CachingService.<>c__DisplayClass28_1`1.<<GetOrAddAsync>b__1>d.MoveNext()22--- End of stack trace from previous location ---
   at LazyCache.CachingService.GetOrAddAsync[T](String key, Func`2 addItemFactory, MemoryCacheEntryOptions policy)
   at TesApi.Web.Management.PriceApiBatchSkuInformationProvider.GetVmSizesAndPricesAsync(String region) in D:\a\1\s\src\ga4gh-tes\src\TesApi.Web\Management\PriceApiBatchSkuInformationProvider.cs:line 64
   at TesApi.Web.ConfigurationUtils.ProcessAllowedVmSizesConfigurationFileAsync() in D:\a\1\s\src\ga4gh-tes\src\TesApi.Web\ConfigurationUtils.cs:line 80
   at TesApi.Web.AllowedVmSizesService.GetAllowedVmSizesImpl() in D:\a\1\s\src\ga4gh-tes\src\TesApi.Web\AllowedVmSizesService.cs:line 43
   at TesApi.Web.AllowedVmSizesService.GetAllowedVmSizes() in D:\a\1\s\src\ga4gh-tes\src\TesApi.Web\AllowedVmSizesService.cs:line 85
   at TesApi.Web.BatchScheduler.GetVmSizeAsync(TesTask tesTask, Boolean forcePreemptibleVmsOnly) in D:\a\1\s\src\ga4gh-tes\src\TesApi.Web\BatchScheduler.cs:line 1618
   at TesApi.Web.BatchScheduler.AddBatchTaskAsync(TesTask tesTask) in D:\a\1\s\src\ga4gh-tes\src\TesApi.Web\BatchScheduler.cs:line 485
   
   at cromwell.backend.impl.tes.TesAsyncBackendJobExecutionActor.handleExecutionError(TesAsyncBackendJobExecutionActor.scala:281)
   at cromwell.backend.impl.tes.TesAsyncBackendJobExecutionActor.handleExecutionFailure(TesAsyncBackendJobExecutionActor.scala:288)
   at cromwell.backend.impl.tes.TesAsyncBackendJobExecutionActor.handleExecutionFailure(TesAsyncBackendJobExecutionActor.scala:63)
   at cromwell.backend.standard.StandardAsyncExecutionActor$$anonfun$handleExecutionResult$11.applyOrElse(StandardAsyncExecutionActor.scala:1346)
   at cromwell.backend.standard.StandardAsyncExecutionActor$$anonfun$handleExecutionResult$11.applyOrElse(StandardAsyncExecutionActor.scala:1342)
   at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:490)
   at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:41
   at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:49)6
   at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
   at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
   at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
   at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

**Comment by BMurri** [comment]
Fixed with #481
