### ISSUE TITLE
Tes compliance: task controller fails during task creation specified in test

### ISSUE THREAD

**Issue by yuliadub** [microsoft/ga4gh-tes#49]
Test makes a POST request to create a task: https://github.com/elixir-cloud-aai/tes-compliance-suite/blob/dev/tests/create_task.yml

Currently the request specified below makes the api return a 500 with an unhandled exception happening in tes. The exception is: 
**fail: Microsoft.AspNetCore.Server.Kestrel[13]
Connection id "0HMNUAE4H87AM", Request id "0HMNUAE4H87AM:00000003": An unhandled exception was thrown by the application.
System.ArgumentNullException: Value cannot be null. (Parameter 'source')
at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
at TesApi.Controllers.TaskServiceApiController.CreateTaskAsync(TesTask tesTask) in D:\a\_work\1\s\src\TesApi.Web\Controllers\TaskServiceApi.cs:line 141**

request body is:     

> request_body: |

      {
        "name": "CompTest",
        "description": "CompTest",
        "executors": [
          {
            "image": "ubuntu:20.04",
            "command": [
              "TestString1",
              "TestString2"
            ]
          },
          {
            "image": "ubuntu:20.04",
            "command": [
              "TestString3",
              "TestString4"
            ]
          }
        ]
      }

**Comment by yuliadub** [comment]
no longer appears to be an issue from the recent successful compliance tes run. https://malibu00.visualstudio.com/Emmons/_releaseProgress?_a=release-environment-logs&releaseId=3969&environmentId=4923
