### ISSUE TITLE
Exception when including any input that does not require any preparation for the node runner

### ISSUE THREAD

**Issue by BMurri** [microsoft/ga4gh-tes#759]
**Describe the bug**
The following exception and stack trace was provided:

> System.NullReferenceException: Object reference not set to an instance of an object.
>    at TesApi.Web.Runner.TaskToNodeTaskConverter.MapInputsAsync(List\`1 inputs, String pathParentDirectory, String containerMountParentDirectory, NodeTaskBuilder builder) in /src/TesApi.Web/Runner/TaskToNodeTaskConverter.cs:line 534
>    at TesApi.Web.Runner.TaskToNodeTaskConverter.BuildInputsAsync(TesTask task, NodeTaskBuilder builder, IList\`1 additionalInputs, String defaultStorageAccount, CancellationToken cancellationToken) in /src/TesApi.Web/Runner/TaskToNodeTaskConverter.cs:line 256
>    at TesApi.Web.Runner.TaskToNodeTaskConverter.ToNodeTaskAsync(TesTask task, NodeTaskConversionOptions nodeTaskConversionOptions, CancellationToken cancellationToken) in /src/TesApi.Web/Runner/TaskToNodeTaskConverter.cs:line 155
>    at TesApi.Web.Runner.TaskExecutionScriptingManager.CreateAndUploadNodeTaskAsync(TesTask tesTask, NodeTaskConversionOptions nodeTaskConversionOptions, CancellationToken cancellationToken) in /src/TesApi.Web/Runner/TaskExecutionScriptingManager.cs:line 124
>    at TesApi.Web.Runner.TaskExecutionScriptingManager.PrepareBatchScriptAsync(TesTask tesTask, NodeTaskConversionOptions nodeTaskConversionOptions, CancellationToken cancellationToken) in /src/TesApi.Web/Runner/TaskExecutionScriptingManager.cs:line 71
>    at TesApi.Web.BatchScheduler.ConvertTesTaskToBatchTaskUsingRunnerAsync(String taskId, TesTask task, String acrPullIdentity, CancellationToken cancellationToken) in /src/TesApi.Web/BatchScheduler.cs:line 930
>    at TesApi.Web.BatchScheduler.AddBatchTaskAsync(TesTask tesTask, CancellationToken cancellationToken) in /src/TesApi.Web/BatchScheduler.cs:line 565
> 

**Steps to Reproduce**
Include an input that points to a single file not using a storage account.

**Expected behavior**
The input is sent as is to the node task runner, with only the Path prefixed for the task working directory.

**Additional context**
Fix is in, testing will be added.

**Comment by BMurri** [comment]
Fixed via #758
